### ISSUE TITLE
Briefly cover how to install PSM 2.01 in the README?

### ISSUE THREAD

**Issue by dogtopus** [OsirizX/ShaRKF00D#1]
All the tutorials I found on Google are either horribly outdated from even first glance or don't work for me. I ended up unpacked the update PKG and directly put the contents under `ux0:/patch` like I was installing nonpdrm games which worked for me, but at that point I already wasted hours trying different stuff and almost corrupted my PKG installer.

**Comment by OsirizX** [comment]
Have you looked at the guide from Samilops? His looks to be the easiest to follow. I'll reference it in the README if you think it's helpful.

https://samilops2.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx

**Comment by dogtopus** [comment]
This is the first thing I saw. However I got a black screen when using PKG installer launcher on 3.65 (both the version mentioned here and the newer version) so I can't install PSM runtime via PKG installer.

**Comment by OsirizX** [comment]
Personally I'd just use pkgj to install 1.0 and then launch any psm game to install the 2.1 update. I'll see if I can get around to writing a tutorial or something.

**Comment by dogtopus** [comment]
~~I thought pkgj was able to install updates the nonpdrm way (i.e. directly extract to patch and refresh livearea/license) so no psm games required. Correct me if I'm wrong.~~ pkgj seems to follow system installation procedure so it's not possible to use pkgj alone.

Seems that it's possible to copy `ux0:bgdl/t/PCSI00011/0000` to `ux0/patch/`, rename to `PCSI00011`, cancel the installation and refresh license/livearea to force install the patch without any PSM app installed. This way only pkgj and vitashell is required.

**Comment by ppekko** [comment]
@dogtopus I found the solution, disable plugins (eg hold L on boot or hold R on henkaku) and then launch.

**Comment by dogtopus** [comment]
@PipeWarp Did you identify the exact plugin that breaks the launcher? Since not everyone can boot the vita with all plugins disabled (e.g. sd2vita users) 

EDIT: okay some simple tests later it seems to be caused by reF00D. Disabling it and PKG installer launches fine.

**Comment by ppekko** [comment]
@dogtopus can you close the issue now

**Comment by ppekko** [comment]
I've also added the instruction to disable plugins in samilop's guide

**Comment by dogtopus** [comment]
@PipeWarp One suggesstion: maybe specifically mention that reF00D causes issue with PKG installer and let user to disable only reF00D first. If they still got a black screen maybe disable all **unnecessary** plugins in `config.txt`. As I mentioned that disabling all plugins/boot to henkaku safe mode is simply not really feasible for some users (like users who use only sd2vita on fat model).
